### ISSUE TITLE
ユーザ登録時の二重登録

### ISSUE THREAD

**Issue by osam023** [Kokemomo/Kokemomo#13]
例えば「hoge（id=1）」というユーザが既に登録されている状態で、「hoge2」のようなユーザを追加すると、「hoge(id=2)」と「hoge2(id=3)」が追加されてしまう。

上記の状態で「hoge」でログインすると、「hoge(id=1)」か「hoge(id=2)」でログインできてしまう。「hoge2」は通常通りログインが可能。

更新時に既存のアカウント名の重複チェックが入っていないために、画面に表示しているアカウントを誤って登録してしまうと考えられるので対策が必要です。

**Comment by hiroki8080** [comment]
ユーザーを単体で登録する仕組みに変更したため解決
