### ISSUE TITLE
アプリケーション開発時に手間のかかる部分がある

### ISSUE THREAD

**Issue by hiroki8080** [Kokemomo/Kokemomo#35]
・モデルのboolean型の値を、hiddenパラメータで扱う際に文字列に変換しなければならない
・db_managerを複数のメソッドの階層に対して渡すことがあり、全てのメソッドの引数にdb_managerと書くのは冗長になったり、書き忘れが発生する

**Comment by matthew70** [comment]
db_managerについてですが
```
engine = KMEngine()
```
のように一箇所で定義し、db_manager変数をどこからでも扱えるようにしたいと考えています。

```
db = KMDBManager()
```

dbをインポートさえすれば、どこからでも扱える感じです。
（DBのセッションについてはsqlalchemyの`scoped_session`を使うことでリクエスト単位でうまく扱えそうです。）
```
from kokemomo.plugins.engine.controller.km_db_manager import db

db.session.add(user)
db.session.commit()
```

**Comment by hiroki8080** [comment]
コメントありがとうございます。
なるほど、ベースモデルが出来るまではその対応で良さそうですね。
ベースモデルが出来たら、モデル内で扱えるように出来ればと思います。
（ベースモデル完成後はコントローラ内ではdb_managerは使わないスタイルです）

**Comment by matthew70** [comment]
> （ベースモデル完成後はコントローラ内ではdb_managerは使わないスタイルです）

今作っているプロトタイプに反映させてみます:bow:

**Comment by matthew70** [comment]
こちらはクローズし、粒度を調整して再イシュー化します。
