### ISSUE TITLE
blogプラグインが動かない

### ISSUE THREAD

**Issue by hiroki8080** [Kokemomo/Kokemomo#40]
アーキテクチャ改修に伴い、プラグインが動作しなくなっている
またテストクラスの追加が必要

**Comment by hiroki8080** [comment]
対応します

**Comment by hiroki8080** [comment]
機能的には動くように調整し、マスターにマージしています。
テストなどはまだ未対応です。

**Comment by masuof** [comment]
CSSの読み込みに関して正常に動作確認しました。

**Comment by hiroki8080** [comment]
一旦クローズして、別チケットにします。
