### ISSUE TITLE
WYSIWYG APIの候補

### ISSUE THREAD

**Issue by masuof** [Kokemomo/Kokemomo#48]
## 概要
現在使用しているTiny MCEはWordPressで実装されたことにより猛烈に普及したが、技術としては古い印象を受けるので、html5機能(contenteditable)を利用した少し先進的なWYSIWYGエディタを候補に挙げてみる。

## 対象APIデモ
左上の鉛筆アイコンをクリックするとページ編集モードになる
http://getcontenttools.com/demo

## 考えられる効果
- より直感的に編集できるようになる

## 検討材料
- 単純に入力UIが変わるだけでなく、定形で使用するhtmlの構文自体を見直すレベルの変更となるため、最終的に期待したい要素を見越して実装に踏み切りたい。

## 参考
- contenteditable自体はie8から対応している(http://caniuse.com/#feat=contenteditable)
- 対象APIはMITライセンス

**Comment by hiroki8080** [comment]
是非サンプルの作成をお願いします！

**Comment by masuof** [comment]
えぇぇぇ～

**Comment by hiroki8080** [comment]
一旦クローズします。
