### ISSUE TITLE
アイコンが欲しい

### ISSUE THREAD

**Issue by hiroki8080** [Kokemomo/Kokemomo#49]
Kokemomoのアイコンが欲しい。
まずはイメージとしては苔桃が描かれていれば何でも良いと思います。

**Comment by masuof** [comment]
ひとまずプロトタイプ的につくりました。
プロジェクトのノリにもよりますが、ソフトウェアのポリシーよりも先にイメージを固めるとすると、どうしても当てずっぽうな作業になてしまうため、本来の作業順序としては、必要な要件を先に固めたいところです。
