### ISSUE TITLE
ブログテーマ制作にあたり

### ISSUE THREAD

**Issue by masuof** [Kokemomo/Kokemomo#53]
テーマ制作にあたり、検討・決定すべき要件を挙げておきます。
## 対応範囲(OS・ブラウザ・バージョン)
 編集対応範囲と閲覧対応範囲は分けて考えるべき

## 機能要件
デザインの対象となる機能が決定されていないため、まず先に機能要件を決定したい。
もしくは、目指すべきサンプルを決定したい。
例
- ブログタイトル
- メニュー 
 - サイトメニュー
 - カテゴリメニュー
 - タグクラウド
- ページタイトル
- 投稿日
- 投稿者
- 本文
- 外部リンク
- twitter機能
- facebook機能
などなどほか多数

**Comment by hiroki8080** [comment]
そうですね、本来は決めておいた方が良いのですが、OS・ブラウザの各バージョンに対応するのはコストがかかりすぎるので、基本的にはjqueryやtwitterbootstrapが対応していればOKという感じで良いと考えています。
なので編集対応範囲と閲覧対応範囲で言うと、今のところ編集はTinyMCE、閲覧はtwitterbootstrapのサポート対象になりますね。

あと、機能要件ですが、まずはブログの閲覧側の基本機能にのみ対応できていれば良いと思います。
現状のテンプレートとしてはkokemomo/plugins/blog/view/templateに、normalという標準テンプレートを作成してありますので、そちらを参考にして頂ければ対象範囲も分かると思います。
